name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: sh .github/workflows/toolchain.sh
    - name: clean
      run: make clean
  coding-style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: check coding style
      run: sh .github/workflows/coding-style.sh